name: Generate Lockfile

on:
  workflow_dispatch:

jobs:
  generate-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Commit lockfile
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package-lock.json
          git commit -m "Add package-lock.json"
          git push
